### ISSUE TITLE
Redisearch: Codec not respected on aggregates

### ISSUE THREAD

**Issue by anderslangballe** [redis-developer/lettucemod#2]
Recently, Redisearch added contains filters on aggregate queries, e.g.:
`FT.AGGREGATE idx * FILTER "contains(@name, 'åæø')"`

However, when using aggregate queries with lettusearch, it seems that the `StringCodec` is not respected unlike when using a select string.

More specifically, the filter string will be added with `RediSearchCommandArgs::add`, whereas the values of select strings are added with `RediSearchCommandArgs::addValue`. The former does not seem to respect the `StringCodec` used. As such, the query I gave above is not possible with this module as far as I can tell since UTF-8 is used.

**Comment by jruaux** [comment]
Thanks for reporting this. I will push an early-access release shortly that hopefully fixes this.

**Comment by anderslangballe** [comment]
Hi, thanks for the quick response!

Unfortunately, it does not seem to make a difference for me. I've initialized my client with `RedisModulesClient.create(...).connect(StringCodec.UTF8))`. I apply my filter with simply `operation(new Filter(...))`. Anywhere I could look/debug to further investigate where it goes wrong?

**Comment by anderslangballe** [comment]
Hi, thanks for the quick response!

I wrote previously that I could not get it to work, but had some old dependencies on my end. I can confirm that it works with the early-access release.

**Comment by anderslangballe** [comment]
One last thing. Is there any way I can avoid having to suppress warnings on unchecked casts with the new generic API? 

For example, I'd prefer not having to suppress warnings in the snippet below:
```
AggregateOptions.AggregateOptionsBuilder<String, String> optionsBuilder = AggregateOptions.builder();
optionsBuilder.operation(new Filter<String>("foo"));
```

**Comment by jruaux** [comment]
Yes, I added key and value generics to Filter and other operations so you shouldn't have any more warnings
