### ISSUE TITLE
Filter Empty Results out of FT.SEARCH

### ISSUE THREAD

**Issue by jGleitz** [redis-developer/lettucemod#21]
When searching with `FT.SEARCH`, RediSearch can return entries with empty content. The Redis Enterprise support informed us that this will not be fixed in RediSearch, but that all clients are expected to filter such results out of the responses themselves. Here’s the doc update for the behaviour: https://github.com/RediSearch/RediSearch/pull/2876

Hence, Lettucemod should filter empty results out of the responses for `FT.SEARCH`.

**Comment by jruaux** [comment]
Thank you for reporting this issue. Are you able to submit the PR against this repo (not your fork)?

**Comment by jGleitz** [comment]
> Are you able to submit the PR against this repo

Oh, how did I manage to file the PR against the wrong repo :facepalm:? Thank you for merging the fix anyway!
