### ISSUE TITLE
ts.mrange and ts.mget does not return proper values when multiple keys are involved

### ISSUE THREAD

**Issue by anirbanbhowmik1511** [redis-developer/lettucemod#22]
<img width="518" alt="Screenshot 2022-08-06 at 12 36 36 PM" src="https://user-images.githubusercontent.com/19996873/183238584-d9080268-c921-4776-82c4-1ae0b5d1a6dc.png">

when mrange or mget query is done and filters matches multiple keys, data mapping is jumbled up.
In screenshot we can see same key is return twice.

**Comment by anirbanbhowmik1511** [comment]
Unable to link issue with the PR.
https://github.com/redis-developer/lettucemod/pull/23

**Comment by jruaux** [comment]
Thank you for your contribution. The PR has been merged and the fix will be included in release 3.0.2
