### ISSUE TITLE
Newest release is not compatible with Spring-Boot version 3.0.0

### ISSUE THREAD

**Issue by shurkanTwo** [redis-developer/lettucemod#29]
I would like to upgrade to spring-boot 3.0.0 and am currently using lettucemod version v3.1.6.
However I am running into some incompatabilities.

The current implementation of the autoconfiguration seems to be incompatible.

Would be awesome if you could have a look! :)

**Comment by jruaux** [comment]
Spring Boot 3 autoconfiguration was added in LettuceMod 3.2.1 (Thanks @zcw159357)
