### ISSUE TITLE
Migrating from spring-redisearch

### ISSUE THREAD

**Issue by murphy-25** [redis-developer/lettucemod#30]
I'm might be confused, but I'm moving from spring-redisearch library to lettucemod. Trying to use StatefulRedisModulesConnection, however I get the following error message: "No qualifying bean of type 'com.redis.lettucemod.api.StatefulRedisModulesConnection<java.lang.String, java.lang.String>' available".

Coming from spring-redisearch I could just autowire StatefulRediSearchConnection and everything would be setup for me. What's changed, is there additional step that I need to do get this auto configuration to be activated.

Thanks,
Murphy.

**Comment by IvanDanilau** [comment]
> I'm might be confused, but I'm moving from spring-redisearch library to lettucemod. Trying to use StatefulRedisModulesConnection, however I get the following error message: "No qualifying bean of type 'com.redis.lettucemod.api.StatefulRedisModulesConnection<java.lang.String, java.lang.String>' available".
> 
> Coming from spring-redisearch I could just autowire StatefulRediSearchConnection and everything would be setup for me. What's changed, is there additional step that I need to do get this auto configuration to be activated.
> 
> Thanks, Murphy.

What's the solution was? Defining the bean explicitly?
