### ISSUE TITLE
Redisearch: GroupBy should be allowed without properties

### ISSUE THREAD

**Issue by anderslangballe** [redis-developer/lettucemod#7]
Currently, there is an assertion to check if at least one property has been specified when grouping:
`LettuceAssert.notEmpty(properties, "Group must have at least one property");`

However, it's possible to group and reduce towards Redisearch without a grouping property, e.g.:
`FT.AGGREGATE idx * GROUPBY 0 REDUCE MIN 1 timestamp AS minTimestamp`

Is there a way to perform such a reduction without GROUPBY, or should the assertion be removed from lettucemod?

**Comment by jruaux** [comment]
Good catch. Thanks! This has been fixed and will be released in version 1.6.2
